// src/services/coinGecko.service.ts
import axios from "axios";

const COINGECKO_BASE = "https://api.coingecko.com/api/v3";

const BINANCE_TO_COINGECKO: Record<string, string> = {
  BTCUSDT: "bitcoin",
  ETHUSDT: "ethereum",
  BNBUSDT: "binancecoin",
  SOLUSDT: "solana",
  XRPUSDT: "ripple",
  ADAUSDT: "cardano",
  DOGEUSDT: "dogecoin",
  TRXUSDT: "tron",
  DOTUSDT: "polkadot",
  MATICUSDT: "polygon",
  LINKUSDT: "chainlink",
  LTCUSDT: "litecoin",
  BCHUSDT: "bitcoin-cash",
  AVAXUSDT: "avalanche-2",
  ATOMUSDT: "cosmos",
  ETCUSDT: "ethereum-classic",
  XLMUSDT: "stellar",
  ICPUSDT: "internet-computer",
  NEARUSDT: "near",
  FILUSDT: "filecoin",

  OPUSDT: "optimism",
  ARBUSDT: "arbitrum",
  INJUSDT: "injective",
  APTUSDT: "aptos",
  SUIUSDT: "sui",
  AAVEUSDT: "aave",
  ALGOUSDT: "algorand",
  ANKRUSDT: "ankr",
  HBARUSDT: "hedera",
  UNIUSDT: "uniswap",

  SHIBUSDT: "shiba-inu",
  PEPEUSDT: "pepe",
  FLOKIUSDT: "floki",
  BONKUSDT: "bonk",
  WIFUSDT: "dogwifhat",
  FETUSDT: "fetch-ai",
  RNDRUSDT: "render-token",
  CHZUSDT: "chiliz",
  WLDUSDT: "worldcoin",
  PAXGUSDT: "pax-gold",

  ZECUSDT: "zcash",
  TONUSDT: "toncoin",
  TIAUSDT: "celestia",
  SEIUSDT: "sei-network",
  JUPUSDT: "jupiter-exchange-solana",
  PYTHUSDT: "pyth-network",
  ARKUSDT: "ark",
  EGLDUSDT: "elrond-erd-2",
  SANDUSDT: "the-sandbox",
  MANAUSDT: "decentraland",

  GALAUSDT: "gala",
  AXSUSDT: "axie-infinity",
  IMXUSDT: "immutable-x",
  FLOWUSDT: "flow",
  KAVAUSDT: "kava",
  RUNEUSDT: "thorchain",
  MINAUSDT: "mina-protocol",
  CRVUSDT: "curve-dao-token",
  LDOUSDT: "lido-dao",
  MKRUSDT: "maker",

  COMPUSDT: "compound-governance-token",
  SNXUSDT: "havven",
  YFIUSDT: "yearn-finance",
  BALUSDT: "balancer",
  ENJUSDT: "enjincoin",
  BATUSDT: "basic-attention-token",
  ZILUSDT: "zilliqa",
  ONEUSDT: "harmony",
  ICXUSDT: "icon",
  QTUMUSDT: "qtum",

  KSMUSDT: "kusama",
  ROSEUSDT: "oasis-network",
  CELOUSDT: "celo",
  DASHUSDT: "dash",
  WAVESUSDT: "waves",
  IOTAUSDT: "iota",
  NEOUSDT: "neo",
  ONTUSDT: "ontology",
  ZRXUSDT: "0x",
  SKLUSDT: "skale",
  LRCUSDT: "loopring",
  OCEANUSDT: "ocean-protocol",
  COTIUSDT: "coti",
  CTSIUSDT: "cartesi",
  BANDUSDT: "band-protocol",
  STORJUSDT: "storj",
  KNCUSDT: "kyber-network-crystal",
  OMGUSDT: "omisego",
  RENUSDT: "republic-protocol",
  ANTUSDT: "aragon",

  ARDRUSDT: "ardor",
  IOSTUSDT: "iostoken",
  SCUSDT: "siacoin",
  DGBUSDT: "digibyte",
  HIVEUSDT: "hive",
  XEMUSDT: "nem",
  STRAXUSDT: "stratis",
  RLCUSDT: "iexec-rlc",
  SUSHIUSDT: "sushi",
  CVCUSDT: "civic",

  STMXUSDT: "storm",
  NKNUSDT: "nkn",
  API3USDT: "api3",
  ALPHAUSDT: "alpha-finance",
  PERPUSDT: "perpetual-protocol",
  LITUSDT: "litentry",
  DODOUSDT: "dodo",
  BAKEUSDT: "bakerytoken",
  TLMUSDT: "alien-worlds",
  BELUSDT: "bella-protocol",

  FLMUSDT: "flamingo-finance",
  SRMUSDT: "serum",
  RAYUSDT: "raydium",
  AUDIOUSDT: "audius",
  AKROUSDT: "akropolis",
  FRONTUSDT: "frontier-token",
  HARDUSDT: "kava-lend",
  KP3RUSDT: "keep3rv1",
  NMRUSDT: "numeraire",
  OGNUSDT: "origin-protocol",

  REEFUSDT: "reef-finance",
  SFPUSDT: "safepal",
  XVSUSDT: "venus",
  PONDUSDT: "marlin",
  UNFIUSDT: "unifi-protocol-dao",
  CVPUSDT: "powerpool",
  FORTHUSDT: "ampleforth-governance-token",
  GRTUSDT: "the-graph",
  LINAUSDT: "linear",
  MBLUSDT: "moviebloc",

  PERLUSDT: "perlin",
  DENTUSDT: "dent",
  HOTUSDT: "holotoken",
  WINUSDT: "wink",
  KEYUSDT: "selfkey",
  VETUSDT: "vechain",
  THETAUSDT: "theta-token",
  TFUELUSDT: "theta-fuel",
  RVNUSDT: "ravencoin",
  CELRUSDT: "celer-network",

  STPTUSDT: "standard-tokenization-protocol",
  TROYUSDT: "troy",
  FIOUSDT: "fio-protocol",
  COSUSDT: "contentos",
  TOMOUSDT: "tomochain",
  CKBUSDT: "nervos-network",
  IRISUSDT: "iris-network",
  VITEUSDT: "vite",
  DOCKUSDT: "dock",
  NULSUSDT: "nuls",

  ILVUSDT: "illuvium",
  APEUSDT: "apecoin",
  GMTUSDT: "stepn",
  GSTUSDT: "green-satoshi-token",
  DYDXUSDT: "dydx",

  FXSUSDT: "frax-share",
  FRAXUSDT: "frax",
  CVXUSDT: "convex-finance",
  SPELLUSDT: "spell-token",
  ACHUSDT: "alchemy-pay",
  IDUSDT: "space-id",

  GMXUSDT: "gmx",
  MAGICUSDT: "magic",
  JOEUSDT: "joe",

  SSVUSDT: "ssv-network",
  RPLUSDT: "rocket-pool",

  CSPRUSDT: "casper-network",
  LQTYUSDT: "liquity",
  ENSUSDT: "ethereum-name-service",
  MASKUSDT: "mask-network",
  C98USDT: "coin98",
  TRUUSDT: "truefi",

  MCUSDT: "merit-circle",
  TWTUSDT: "trust-wallet-token",
  XNOUSDT: "nano",
  KLAYUSDT: "klay-token",

  GLMRUSDT: "moonbeam",
  MOVRUSDT: "moonriver",
  ASTRUSDT: "astar",
  CFGUSDT: "centrifuge",

  AGLDUSDT: "adventure-gold",
  DARUSDT: "mines-of-dalarnia",
  ALPACAUSDT: "alpaca-finance",
  DEGOUSDT: "dego-finance",
  USTCUSDT: "terrausd",
  LUNCUSDT: "terra-luna",
  HFTUSDT: "hashflow",
  BLURUSDT: "blur",
  EDUUSDT: "open-campus",
};

export async function getIconUrlForSymbol(
  binanceSymbol: string
): Promise<string | undefined> {
  const key = binanceSymbol.toUpperCase(); // 👉 BTCUSDT
  const cgId = BINANCE_TO_COINGECKO[key]; // ✅ এখন match হবে
  if (!cgId) return undefined;

  const url = `${COINGECKO_BASE}/coins/${cgId}`;
  const res = await axios.get(url, {
    params: {
      localization: "false",
      tickers: "false",
      market_data: "false",
      community_data: "false",
      developer_data: "false",
      sparkline: "false",
    },
  });

  const image = res.data?.image;
  return image?.small || image?.thumb || image?.large;
}
